name: dashchain
description: A Dart library to work with some crypto exchanges. Get latest cryptomarket quotes, check order books, write backtests, manage your assets !
version: 0.7.0
homepage: https://github.com/Nanodash/dashchain

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  http: ^0.13.4
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0


dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.1
  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  import_sorter: ^4.6.0

# run with `dart run import_sorter:main`
import_sorter:
  emojis: false
  comments: false
  ignore_files:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
