name: dashchain
description: A blockchain project.
version: 0.0.1
homepage: https://github.com/Nanodash/dashchain

environment:
  sdk: '>=2.12.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.16.0
