name: dashchain
description: A Dart library to work with some crypto exchanges.
version: 0.0.1
homepage: https://github.com/Nanodash/dashchain

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  http: ^0.13.3


dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.16.0
